variables:
  DOCKER_REG: dk.jingli365.com
  DOCKER_NAME: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME
  DOCKER_CI_NAME: $DOCKER_REG/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME:$CI_COMMIT_SHA
  DOCKER_BRANCH_NAME: $DOCKER_REG/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG
  JL_APP_COMMAND: node server.js
  JL_APP_PORT: 8080
  JL_APP_LINK_VERSION: 2
  JL_APP_INIT_TESTDATA: "false"

stages:
  - build
  - docker
  - deploy

image: docker:git

before_script:
  - 'eval $(ssh-agent -s) && echo "$SSH_PRIVATE_KEY">.k && chmod 600 .k && ssh-add .k && rm -f .k'
  - 'mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\tSendEnv JL_APP_*\n\n" > ~/.ssh/config'

build:dist:
  stage: build
  only:
    - branches
  image: $DOCKER_REG/jl-build:v4
  tags:
    - serial
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - dist/
  script:
    - git submodule update --init --checkout
    - npmcache
    - npm install
    - gulp tarball -n $CI_COMMIT_REF_SLUG

build:image:
  stage: docker
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - dist/
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker build . -t $DOCKER_CI_NAME  --build-arg NPM_TOKEN=$NPM_TOKEN
    - docker push $DOCKER_CI_NAME

.deploy_template: &deploy_template
  stage: deploy
  environment:
    name: $ENVIROMENT_NAME
    url: https://$ENVIROMENT_HOST/proj/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME/
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_BRANCH_NAME
    - docker push $DOCKER_BRANCH_NAME
    - echo deploy to $CI_ENVIRONMENT_URL
    - ssh test@$ENVIROMENT_HOST /home/test/bin/docker_service.sh $DOCKER_REG $DOCKER_NAME $CI_COMMIT_REF_SLUG $CI_ENVIRONMENT_SLUG -p $JL_APP_PORT

.common_variables: &common_variables
    JL_APP_DEBUG: 0
    JL_APP_HOST: $CI_ENVIRONMENT_URL
    JL_APP_REDIS: redis://l.jingli365.com:16379
    JL_APP_COMAPI_HOST: api.$ENVIROMENT_HOST
    JL_APP_COMAPI_PORT: 14101
    JL_APP_BUDGET_HOST: $ENVIROMENT_HOST
    JL_APP_BUDGET_PORT: 14103
    JL_APP_NOTICE_EMAIL: testteam@jingli365.com
    JL_APP_V2_HOST: https://$ENVIROMENT_HOST/index-v2.html
    JL_APP_APPROVE_SERVER_URL: https://$ENVIROMENT_HOST/proj/svr-trip-approve/api/v1
    JL_APP_TMC: https://$ENVIROMENT_HOST/proj/svr-tmc
    JL_APP_TMC_FAKE: 0
    JL_APP_TD_MONITORURL: https://$ENVIROMENT_HOST/proj/old-qmtrip/api/v1/tripDetail
    JL_APP_CLOUDKEY: jinglicloud2017
    JL_APP_CLOUDAPI: https://$ENVIROMENT_HOST/proj/svr-jlbudget/api/v1
    JL_APP_CLOUD: https://$ENVIROMENT_HOST/proj/web-cloud-mgr
    JL_APP_CLOUD_APP_ID: 756b12b3-e243-41ae-982f-dbdfb7ea7e92
    JL_APP_CLOUD_APP_SECRET: 6c8f2cfd-7aa4-48c7-9d5e-913896acec12
    JL_APP_ORDER_LINK: https://$ENVIROMENT_HOST/svc/java-jingli-order1
    JL_APP_ORDER_APP_ID: 756b12b3-e243-41ae-982f-dbdfb7ea7e92
    JL_APP_ORDER_APP_SECRET: 6c8f2cfd-7aa4-48c7-9d5e-913896acec12
    JL_APP_MALL_ORDER_LINK: https://$ENVIROMENT_HOST/svc/java-jingli-mall
    JL_APP_MALL_APP_ID: 756b12b3-e243-41ae-982f-dbdfb7ea7e92
    JL_APP_MALL_APP_SECRET: 6c8f2cfd-7aa4-48c7-9d5e-913896acec12
    JL_APP_PAY_ORDER_LINK: https://$ENVIROMENT_HOST/svc/java-jingli-pay
    JL_APP_PAY_APP_ID: 756b12b3-e243-41ae-982f-dbdfb7ea7e92
    JL_APP_PAY_APP_SECRET: 6c8f2cfd-7aa4-48c7-9d5e-913896acec12
    JL_APP_PERMISSION_ORDER_LINK: https://$ENVIROMENT_HOST/svc/java-jingli-auth
    JL_APP_PERMISSION_APP_ID: 756b12b3-e243-41ae-982f-dbdfb7ea7e92
    JL_APP_PERMISSION_APP_SECRET: 6c8f2cfd-7aa4-48c7-9d5e-913896acec12
    JL_APP_JAVA_GETWAY: https://$ENVIROMENT_HOST
    JL_APP_OPENAPI_APP_ID: 8218a6b0-2d74-11e8-9997-218659f8f259
    JL_APP_OPENAPI_APP_SECRET: ffdfbf70-2d74-11e8-9997-218659f8f259
    JL_APP_ORDERVALIDATE_APP_ID: 756b12b3-e243-41ae-982f-dbdfb7ea7e92
    JL_APP_ORDERVALIDATE_APP_SECRET: 6c8f2cfd-7aa4-48c7-9d5e-913896acec12
    JL_APP_ACTIVITY_APP_ID: 756b12b3-e243-41ae-982f-dbdfb7ea7e92
    JL_APP_ACTIVITY_APP_SECRET: 6c8f2cfd-7aa4-48c7-9d5e-913896acec12

deploy:master:
  <<: *deploy_template
  only:
    - /^master$/
  variables:
    <<: *common_variables
    ENVIROMENT_NAME: master
    ENVIROMENT_HOST: l.jingli365.com
    JL_APP_DEBUG: 1
    JL_APP_POSTGRES: postgres://times:time0418@l.jingli365.com:15432/times
    JL_APP_COMAPI_PORT: 14101
    JL_APP_BUDGET_PORT: 14103

deploy:test:
  <<: *deploy_template
  only:
    - /^test$/
    - /^review\//
  variables:
    <<: *common_variables
    ENVIROMENT_NAME: test
    ENVIROMENT_HOST: t.jingli365.com
    JL_APP_POSTGRES: postgres://times:time0418@t.jingli365.com:15432/time_test
    JL_APP_COMAPI_PORT: 14201
    JL_APP_BUDGET_PORT: 14113

deploy:release:
  <<: *deploy_template
  only:
    - /^release$/
  when: manual
  variables:
    <<: *common_variables
    ENVIROMENT_NAME: release
    ENVIROMENT_HOST: j.jingli365.com
    JL_APP_POSTGRES: postgres://jingli:J1n9L1.t3ch@j.jingli365.com:5432/qmtrip
    JL_APP_REDIS: redis://j.jingli365.com
    JL_APP_COMAPI_PORT: 4201
    JL_APP_BUDGET_PORT: 4103
    JL_APP_NOTICE_EMAIL: tbudget@jingli365.com

deploy:demo:
  <<: *deploy_template
  only:
    - /^demo$/
  when: manual
  variables:
    <<: *common_variables
    ENVIROMENT_NAME: demo
    ENVIROMENT_HOST: demo.jingli365.com
    JL_APP_POSTGRES: postgres://jingli:J1n9L1.t3ch@j.jingli365.com:5432/qmtrip-demo
    JL_APP_REDIS: redis://demo.jingli365.com
    JL_APP_COMAPI_PORT: 4201
    JL_APP_BUDGET_PORT: 24103
    JL_APP_NOTICE_EMAIL: tbudget@jingli365.com
    JL_APP_TMC: https://j.jingli365.com/proj/svr-tmc

deploy:tester:
  <<: *deploy_template
  when: manual
  variables:
    <<: *common_variables
    ENVIROMENT_NAME: tester-$GITLAB_USER_ID
    ENVIROMENT_HOST: tester-$GITLAB_USER_ID.l.jingli365.com
    JL_APP_POSTGRES: postgres://test:JingliTest0418@dockerhost:15432/tester_$GITLAB_USER_ID
    JL_APP_POSTGRES_INITDB: tester_$GITLAB_USER_ID
    JL_APP_REDIS: redis://dockerhost:16379
    JL_APP_COMAPI_HOST: l.jingli365.com
    JL_APP_COMAPI_PORT: 14101
    JL_APP_BUDGET_PORT: 14103
    JL_APP_APPROVE_SERVER_URL: https://l.jingli365.com/proj/svr-trip-approve/api/v1
    JL_APP_TMC: http://l.jingli365.com/proj/svr-tmc
    JL_APP_CLOUDAPI: https://l.jingli365.com/proj/svr-jlbudget/api/v1
    JL_APP_CLOUD: https://l.jingli365.com/cloud
    JL_APP_ORDER_LINK: https://l.jingli365.com/svc/java-jingli-order1
    JL_APP_MALL_ORDER_LINK: https://l.jingli365.com/svc/java-jingli-mall
    JL_APP_PERMISSION_ORDER_LINK: https://l.jingli365.com/svc/java-jingli-auth
  script:
    - docker login -u dockeruser -p $DOCKER_PASSWD $DOCKER_REG
    - docker pull $DOCKER_CI_NAME
    - docker tag $DOCKER_CI_NAME $DOCKER_REG/$DOCKER_NAME:tester-$GITLAB_USER_ID
    - docker push $DOCKER_REG/$DOCKER_NAME:tester-$GITLAB_USER_ID
    - echo deploy to $CI_ENVIRONMENT_URL
    - ssh test@l.jingli365.com /home/test/bin/docker_service.sh $DOCKER_REG $DOCKER_NAME tester-$GITLAB_USER_ID tester-$GITLAB_USER_ID -p 8080
