module.exports = [
    {
        "No": "K1247",
        "agents": [ {"name":"ctrip","cabins":[{"name":2, "price":620}]} ],
        "departDateTime": "2017-03-18 16:29 +0800",
        "arrivalDateTime": "2017-03-20 05:51 +0800",
        "originPlace":
        { "id": "CT_132",
            "skyCode": "CCKG-sky",
            "baiduCode": "132",
            "name": "重庆",
            "pinyin": "chongqing",
            "letter": "CQS",
            "latitude": 29.544606,
            "longitude": 106.530635,
            "parentId": "",
            "cityLevel": 10000,
            "didaCode": "6140323",
            "type": 2,
            "ctripCode": "CKG",
            "enName": null,
            "isAbroad": false,
            "timezone": "Asia/Chongqing",
            "offsetUtc": 28800 },
    "destination":
        { "id": "CT_179",
            "skyCode": "CHGH-sky",
            "baiduCode": "179",
            "name": "杭州",
            "pinyin": "hangzhou",
            "letter": "HZS",
            "latitude": 30.259244,
            "longitude": 120.219375,
            "parentId": "CT_29",
            "cityLevel": 10000,
            "didaCode": "1454",
            "type": 2,
            "ctripCode": "HGH",
            "enName": null,
            "isAbroad": false,
            "timezone": "Asia/Shanghai",
            "offsetUtc": 28800 },
    "duration": 2242,
    "originStation": "重庆",
    "destinationStation": "杭州",
    "type": 0 }
    ]